const prompts = [
    "Write a tweet about the latest tech trends in AI development within 220-280 characters.",
    "Create a tweet discussing the importance of clean code practices. Keep it within 280 characters.",
    "Generate a humorous tweet about remote work struggles for developers, within 280 characters.",
    "Write an engaging tweet sharing tips for debugging complex code, within 280 characters.",
    "Create a motivational tweet for aspiring software engineers. Keep it under 280 characters.",
    "Generate a tweet about the impact of code reviews on software quality, within 280 characters.",
    "Write a tweet discussing best practices for version control systems like Git, within 280 characters.",
    "Create a tweet sharing the differences between Frontend vs Backend development, within 280 characters.",
    "Generate a tweet about common security vulnerabilities developers should avoid, within 280 characters.",
    "Write a tweet explaining why code documentation is essential for maintaining large projects, within 280 characters.",
    "Discuss the pros and cons of using serverless architecture in modern applications, within 280 characters.",
    "Create a tweet sharing tips for improving API performance, within 280 characters.",
    "Generate a tweet about the importance of version control in collaborative projects, within 280 characters.",
    "Write a tweet on how to effectively manage state in a React application, within 280 characters.",
    "Create a tweet discussing the future of web development in a post-React ecosystem, within 280 characters.",
    "Generate a tweet about the impact of blockchain technology on software development, within 280 characters.",
    "Write a tweet highlighting key differences between SQL and NoSQL databases, within 280 characters.",
    "Discuss the role of containerization in modern software deployment, within 280 characters.",
    "Create a tweet sharing why performance optimization is critical for large-scale web applications, within 280 characters.",
    "Generate a tweet about the challenges and solutions for cross-platform mobile app development, within 280 characters.",
    "Write a tweet about the significance of agile methodology in managing software development teams, within 280 characters.",
    "Write a tweet discussing the impact of artificial intelligence on software testing, within 280 characters.",
    "Create a tweet explaining how microservices architecture enhances scalability, within 280 characters.",
    "Generate a tweet about the differences between monolithic and microservices architectures, within 280 characters.",
    "Write a tweet sharing insights on the importance of proper API documentation, within 280 characters.",
    "Create a tweet discussing the role of database optimization in software performance, within 280 characters.",
    "Generate a tweet about the evolution of DevOps practices and their impact on software delivery, within 280 characters.",
    "Write a tweet about the challenges of managing legacy codebases, within 280 characters.",
    "Create a tweet discussing how to handle code reviews effectively, within 280 characters.",
    "Generate a tweet about the importance of accessibility in software development, within 280 characters.",
    "Write a tweet explaining how to implement authentication and authorization securely, within 280 characters.",
    "Create a tweet sharing why testing-driven development (TDD) is crucial for quality assurance, within 280 characters.",
    "Generate a tweet on the benefits of using TypeScript over JavaScript in large-scale projects, within 280 characters.",
    "Write a tweet discussing the role of cloud computing in modern software development, within 280 characters.",
    "Create a tweet about common pitfalls in API design and how to avoid them, within 280 characters.",
    "Generate a tweet explaining the concept of event-driven architecture, within 280 characters.",
    "Write a tweet sharing how to choose the right database for your project needs, within 280 characters.",
    "Create a tweet discussing best practices for developing and maintaining a microservices ecosystem, within 280 characters.",
    "Generate a tweet about the role of analytics in improving software application performance, within 280 characters.",
    "Write a tweet on how to handle technical debt in software projects, within 280 characters.",
    "Create a tweet discussing the challenges of transitioning from Waterfall to Agile development, within 280 characters.",
    "Generate a tweet about the importance of performance monitoring and debugging, within 280 characters.",
    "Write a tweet sharing how to build a scalable architecture for a high-traffic web application, within 280 characters.",
    "Create a tweet on how to implement reactive programming concepts effectively, within 280 characters.",
    "Generate a tweet discussing the role of automated testing in reducing development time, within 280 characters.",
    "Write a tweet highlighting how to manage state in a stateful system, within 280 characters.",
    "Create a tweet discussing the importance of versioning and branching strategies in software projects, within 280 characters.",
    "Generate a tweet about the challenges of handling cross-browser compatibility, within 280 characters.",
    "Write a tweet sharing best practices for maintaining a monorepo in modern software development, within 280 characters.",
    "Create a tweet on how to optimize database queries for faster data retrieval, within 280 characters.",
    "Generate a tweet discussing the evolution of software development methodologies over the past decade, within 280 characters.",
    "Write a tweet highlighting how to balance security and usability in web application design, within 280 characters.",
    "Create a tweet about the significance of developer tools in enhancing productivity, within 280 characters.",
    "Generate a tweet discussing the role of micro frontends in modern web application architectures, within 280 characters.",
    "Write a tweet sharing how to implement a CI/CD pipeline efficiently, within 280 characters.",
    "Create a tweet discussing how to handle database migrations in a microservices environment, within 280 characters.",
    "Generate a tweet explaining how feature flags improve the software release process, within 280 characters.",
    "Write a tweet sharing tips for optimizing front-end performance, within 280 characters.",
    "Create a tweet on how to maintain data integrity in distributed databases, within 280 characters.",
    "Generate a tweet discussing the role of container orchestration tools like Kubernetes, within 280 characters.",
    "Write a tweet about how to balance maintaining code quality with shipping new features, within 280 characters.",
    "Create a tweet discussing the evolution of test automation in agile development, within 280 characters.",
    "Generate a tweet about the challenges of handling large-scale data processing, within 280 characters.",
    "Write a tweet sharing how to implement microservices in a serverless environment, within 280 characters.",
    "Create a tweet explaining how to implement a RESTful API that adheres to best practices, within 280 characters.",
];
export default prompts;
